### ISSUE TITLE
Issue with halt and resuming

### ISSUE THREAD

**Issue by JessNielsen** [ovr/perfect-php-vagrant#6]
I am having issues with running vagrant up after a halt, and the server doesnt work anymore. It gives a "server error". The only thing i changed is the default host settings in /etc/nginx/sites-enabled/default.

**Comment by JessNielsen** [comment]
I decided to try again with fresh clone of this repo. This time i used the projects folder in my user dir. it synced and i got the hosts to work. but this time i am unable to get write prmissions for any dir. Volt cache need this to work.
My previous setup was a quick and dirty thing in the localhost dir, where everything is owned by vagrant. Nothing ever malfunctioned there, in regards to file operations.

So now i have a second issue, which might or might not be related to this. i opened a new issue for it.

**Comment by JessNielsen** [comment]
Reloading (vagrant halt && vagrant destroy -f && vagrant up) the server fixes the problem but first time i did that, it lasted only a single session.

**Comment by ovr** [comment]
Sorry for a long delay, I didnt see you issue :(
I think provision was fails in the first time when you was trying to run it
In second trying all is okey

I will close this issue via it seems to be okey
If you have got any questions about this issue you can in this issue

Have a nice day :3
